export const taxis = [
  {
    id: 'taxi1',
    driver: 'Ahmed Benali',
    plate: 'A-12345-BM',
    rating: 4.8,
    description: 'Clean car, available 24/7',
    coordinates: { latitude: 33.5731, longitude: -7.5898 },
    locationName: 'Centre-ville de Casablanca',
  },
  {
    id: 'taxi2',
    driver: 'Fatima Zahra',
    plate: 'B-67890-CM',
    rating: 4.6,
    description: ' Professional and polite',
    coordinates: { latitude: 33.5885, longitude: -7.6032 },
    locationName: 'Ain Diab',
  },
  {
    id: 'taxi3',
    driver: 'Mohamed Idrissi',
    plate: 'C-11223-DM',
    rating: 4.9,
    description: ' Fast and safe',
    coordinates: { latitude: 33.6057, longitude: -7.6210 },
    locationName: 'Sidi Belyout / Port de Casablanca',
  },
  {
    id: 'taxi4',
    driver: 'Sara El Amrani',
    plate: 'D-44556-EM',
    rating: 4.7,
    description: ' Friendly and courteous',
    coordinates: { latitude: 33.6000, longitude: -7.6325 },
    locationName: 'Hay Hassani',
  },
  {
    id: 'taxi5',
    driver: 'Hassan Boukili',
    plate: 'E-77889-FM',
    rating: 4.5,
    description: ' Experienced and comfortable',
    coordinates: { latitude: 33.5920, longitude: -7.5700 },
    locationName: 'Maarif',
  },
  {
    id: 'taxi6',
    driver: 'Karim El Fassi',
    plate: 'F-99887-GM',
    rating: 4.4,
    description: ' Reliable and friendly',
    coordinates: { latitude: 33.5731, longitude: -7.5898 },
    locationName: 'Centre-ville de Casablanca',
  },
  {
    id: 'taxi7',
    driver: 'Leila Amrani',
    plate: 'G-77665-HM',
    rating: 4.6,
    description: ' Clean and safe',
    coordinates: { latitude: 33.5735, longitude: -7.6450 },
    locationName: 'Oulfa',
  },
];
